version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "./src/backend"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "13:00"
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "./src/frontend"
    open-pull-requests-limit: 4
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "13:00"
